FOLDER: './experiments' # Experiment files saving path

TEST:
  FOLDER: './results' # Testing files saving path

DATASET:
  SMPL_PATH: 'deps/smpl'
  TRANSFORM_PATH: 'deps/transforms/'
  WORD_VERTILIZER_PATH: 'deps/t2m/glove/'
  HUMANML3D:
    ROOT: 'datasets/humanml3d' # HumanML3D directory
    SPLIT_ROOT: 'datasets/humanml3d' # HumanML3D splits directory
  # 以下是2025.5.29 修改的内容，要使用我们的Scene数据集
  HUMANML3D_SCENE:
    ROOT: 'datasets/humanml3d_scene' # HumanML3D Scene directory
    SPLIT_ROOT: 'datasets/humanml3d_scene' # HumanML3D Scene splits directory


model:
  clip_path: 'deps/clip-vit-large-patch14' # bert model path for all text encoders
  # motion_clip_path: 'deps/motionclip'
  t2m_path: 'deps/t2m/t2m'


