####################################
# The following are general settings
####################################

# Experiment name, more details in Section 'Experiment Name Explanation'
#use 1029_mclip_removestylemlp_transadaln for mld.py
NAME: Varsapura_from_scratch_1219
# Debug mode. Set to True will enter the debug mode, then the program will
# 1. use a tiny dataset for trianing and evaluation
# 2. validate more intensively
# 3. will not use `wandb logger`
DEBUG: False
# Devices. Optional: “cpu”, “gpu”
ACCELERATOR: 'gpu'
# Index of GPUs eg. [0] or [0,1,2,3]
DEVICE: [0]

#####################################
# The following are training settings
#####################################
TRAIN:
  # Model stage. Optional: "vae", "diffusion"
  STAGE: diffusion
  # Training dataset name
  DATASETS: ['humanml3d']
  # Number of dataloader workers
  NUM_WORKERS: 1
  # Size of batches
  BATCH_SIZE: 128
  # Total epochs for training
  END_EPOCH: 2000

  # RESUME: '/root/autodl-tmp/MyRepository/MCM-LDM/experiments/mld/Varsapura_from_scratch_1216/checkpoints/epoch=49.ckpt' # Resume training from this path
  RESUME: ''
  PRETRAINED_VAE: 'checkpoints/vae_checkpoint/vae7.ckpt' # vae model path
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 1e-4 # Learning rate
  # Ablation study configurations.
  ABLATION:
    SKIP_CONNECT: True
    PE_TYPE: mld
    DIFF_PE_TYPE: mld

#####################################
# The following are validation settings
#####################################
EVAL:
  DATASETS: ['humanml3d'] # Evaluating datasets
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: test

#####################################
# The following are testing settings
#####################################
TEST:
  # CHECKPOINTS: 'checkpoints/denoiser_checkpoint/denoiser.ckpt' # our model path
  CHECKPOINTS: '/root/autodl-tmp/MyRepository/MCM-LDM/experiments/mld/Varsapura_from_scratch_1220/checkpoints/epoch=799.ckpt'
  # CHECKPOINTS: '/root/autodl-tmp/MyRepository/MCM-LDM/experiments/mld/Varsapura_from_scratch_1218/checkpoints/epoch=349.ckpt'
  #CHECKPOINTS: ./models/mld_humanml3d_checkpoint/1222_mld_humanml3d_FID041.ckpt # Pretrained model path
  DATASETS: ['humanml3d'] # training datasets
  SPLIT: test
  BATCH_SIZE: 128 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1

#####################################
# The following are basic datasets settings
#####################################
DATASET:
  JOINT_TYPE: 'humanml3d' # join type

BASELINEABLATION:
  TRANSGET4: True
  CONTENT_DROPOUT: True

#####################################
# The following are metric settings
#####################################
METRIC:
  TYPE: ['TemosMetric', 'TM2TMetrics']

#####################################
# The following are training losses settings
#####################################
LOSS:
  TYPE: mld # Losses type
  LAMBDA_LATENT: 1.0e-5 # Lambda for latent Losses
  LAMBDA_KL: 1.0e-4 # Lambda for kl Losses
  LAMBDA_REC: 1.0 # Lambda for reconstruction Losses
  LAMBDA_GEN: 1.0 # Lambda for text-motion generation losses
  LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
  LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
  LAMBDA_PRIOR: 0.0
  DIST_SYNC_ON_STEP: False # Sync Losses on step when distributed trained

#####################################
# The following are basic model settings
#####################################
model:
  vae: true # whether vae model
  model_type: mld # model type
  condition: 'text'
  latent_dim: [7, 256] # latent dimension
  ff_size: 1024 #
  num_layers: 9 # number of layers
  num_head: 4 # number of head layers
  droupout: 0.1 # dropout rate
  activation: gelu # activation type
  guidance_scale: 5 #7.5 5
  guidance_uncondp: 0.25 # 0.1 0.25

#####################################
# The following are loggers settings
#####################################
LOGGER:
  SACE_CHECKPOINT_EPOCH: 50
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 100
  TENSORBOARD: True
  WANDB:
    PROJECT: null
    OFFLINE: False
    RESUME_ID: null

TRAJECTORY:
  ENABLED: True  # 是False的话会用content的轨迹
  # ================= 架构相关 =================
  # 是否启用强力注入 (Concat 方式)
  # 如果 False，则回退到原始的 AdaLN 弱注入
  INJECTION_MODE: 'concat'  # options: 'concat', 'adaln'
  
  # 轨迹编码器类型
  # 'seq': 输出序列 (我们改的那版)
  # 'pool': 输出单个 Token (MCM-LDM 原版)
  ENCODER_TYPE: 'seq'

  # ================= 训练策略 =================
  # 旋转增强 (解决解耦的核心)
  AUGMENTATION:
    ENABLED: True
    ROTATION_RANGE: 90.0  # 角度范围 +/- 90度
  
  # 根节点屏蔽 (双重保险,屏蔽263维特征向量的前4维)
  ROOT_MASKING_DIM4: True
  
  # Content Dropout (逼迫模型看轨迹)
  USE_CONTENT_DROPOUT: True
  CONTENT_DROPOUT_PROB: 0.5

  # ================= 推理引导 (默认值) =================
  # 这些可以在推理脚本中覆盖，但这里设个默认值
  GUIDANCE:
    ENABLED: False
    STRENGTH: 2.0
    GUIDANCE_START : 1000  # 去噪开启引导的开始step和结束step
    GUIDACE_END: 0

    WAYPOINTS_MODE: True # 是否启用关键路点追踪功能
    WAYPOINTS_GUIDE_STRENGTH: 100.0
    WAYPOINTS_INTERVAL: 10  # 每多少帧做一次路径点的指引

    OBSTACLE_MODE: True  # 是否启用避障功能
    OBSTACLE_GUIDE_STRENGTH: 2.0

    STRICT_TRACK_MODE: False  # 是否要严格按照轨迹来走（效果比较差，不建议启用）
    STRICT_TRACK_STRENGTH: 2.0

