# configs/config_physimos_probe.yaml
# This config is for the PhysiMoS technical probe, fine-tuning MCM-LDM.
# This is a full config file, not using 'defaults', to avoid any key conflicts.

####################################
# The following are general settings
####################################
NAME: "PhysiMoS_Finetune_v2_0114_3scenes" #<-- 1. MODIFIED
FOLDER_EXP: "experiments/physimos_probe"   #<-- 2. NEW
DEBUG: False
ACCELERATOR: 'gpu'
DEVICE: [0]

#####################################
# The following are training settings
#####################################
TRAIN:
  STAGE: diffusion
  DATASETS: ['PHYSIMOS100STYLE'] #<-- 3. MODIFIED 
  NUM_WORKERS: 4 #<-- Can increase if IO is a bottleneck
  BATCH_SIZE: 16 #<-- 4. MODIFIED
  END_EPOCH: 2000 #<-- 5. MODIFIED

  RESUME: '' 
  PRETRAINED_VAE: 'checkpoints/vae_checkpoint/vae7.ckpt'
  PRETRAINED: 'checkpoints/denoiser_checkpoint/denoiser.ckpt' 
  OPTIM:
    TYPE: AdamW
    LR: 2e-5
  ABLATION:
    SKIP_CONNECT: True
    PE_TYPE: mld
    DIFF_PE_TYPE: mld

#####################################
# The following are validation settings
#####################################
EVAL:
  DATASETS: ['PHYSIMOS100STYLE'] #<-- 6. MODIFIED (Good practice to eval on the same dist)
  BATCH_SIZE: 16
  SPLIT: test

#####################################
# The following are testing settings
#####################################
TEST:
  # CHECKPOINTS: 'checkpoints/denoiser_checkpoint/denoiser.ckpt' #<-- 7. [CRITICAL] UPDATE THIS PATH
  # CHECKPOINTS: '/root/autodl-tmp/MyRepository/MCM-LDM/experiments/mld/PhysiMoS_Probe_Finetune_v1/checkpoints/epoch=849.ckpt'
  # CHECKPOINTS: '/root/autodl-tmp/MyRepository/MCM-LDM/experiments/mld/debug--PhysiMoS_Finetune_v2_1125_3scenes/checkpoints/epoch=649.ckpt' #<-- 12. MODIFIED
  CHECKPOINTS: '/root/autodl-tmp/MyRepository/MCM-LDM/experiments/mld/debug--PhysiMoS_Finetune_v2_0114_3scenes/checkpoints/epoch=699.ckpt' #<-- 13. MODIFIED
  DATASETS: ['PHYSIMOS100STYLE']
  SPLIT: test
  BATCH_SIZE: 16
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1

#####################################
# The following are basic datasets settings
#####################################
DATASET:
  SPLIT_DIR: './datasets/100StyleDataset'
  JOINT_TYPE: 'humanml3d'
  SAMPLER:
    MAX_LEN: 420  # 用这个新的应该会覆盖原来的，100Style数据集的分布会比较广泛一点，长数据比较多
    MIN_LEN: 40
  # ==> 8. ADDED NEW DATASET CONFIGURATION
  
  PHYSIMOS100STYLE:
    ROOT: "./datasets/PhysicsDataset"
    UNIT_LEN: 4
    SCENE_MAPPING_PATH: "./datasets/100StyleDataset/scenes.json"
    STYLE_SUBSET:
      - "Front"
      - "Back"
      - "Left"
      - "Right"
      - "FrontLeft"
      - "FrontRight"
      - "BackLeft"
      - "BackRight"

#####################################
# The following are metric settings
#####################################
METRIC:
  TYPE: ['TemosMetric', 'TM2TMetrics'] # Keep for now, can be commented out if they cause issues

#####################################
# The following are training losses settings
#####################################
LOSS:
  TYPE: mld
  LAMBDA_LATENT: 1.0e-5
  LAMBDA_KL: 1.0e-4
  LAMBDA_REC: 1.0
  LAMBDA_GEN: 1.0
  LAMBDA_CROSS: 1.0
  LAMBDA_CYCLE: 0.0
  LAMBDA_PRIOR: 0.0
  DIST_SYNC_ON_STEP: False

#####################################
# The following are basic model settings
#####################################
model:
  vae: true
  model_type: mld
  condition: 'text' # This will be effectively ignored by our model changes later
  latent_dim: [7, 256]
  ff_size: 1024
  num_layers: 9
  num_head: 4
  dropout: 0.1
  activation: gelu
  guidance_scale: 5
  guidance_uncondp: 0.25
  scene_cat_dim: 1
  # [修改] 物理向量的长度是 4: [wind_x, wind_y, wind_mag, ceiling_height]
  phys_params_dim: 4 

#####################################
# The following are loggers settings
#####################################
LOGGER:
  SACE_CHECKPOINT_EPOCH: 50 #<-- 9. MODIFIED
  LOG_EVERY_STEPS: 1
  VAL_EVERY_STEPS: 20 #<-- 10. MODIFIED
  TENSORBOARD: True
  WANDB:
    PROJECT: 'mld-physimos-probe' #<-- 11. MODIFIED
    OFFLINE: True
    RESUME_ID: null

DEMO:
  content_motion_dir: '/root/autodl-tmp/MyRepository/MCM-LDM/demo/content_motion'
  # PHYSICS_JSON: '/root/autodl-tmp/MyRepository/MCM-LDM/heavy.json'
  PHYSICS_JSON: '/root/autodl-tmp/MyRepository/MCM-LDM/heavy.json'


#####################################
# Physics Global Switch
#####################################
# 新增这个字段，设置为 False 即可关闭物理影响
ENABLE_PHYSICS: False
DRAW_ATTN_MAP: False

#####################################
# Trajectory Guidance Settings
#####################################
TRAJECTORY:
  GUIDANCE:
    ENABLED: True   
    GUIDANCE_START: 1000      # 开始引导的时间步 (t)
    GUIDACE_END: 0            # 结束引导的时间步
    WAYPOINTS_MODE: True          # 是否开启路径点引导
    WAYPOINTS_GUIDE_STRENGTH: 500000.0 # 引导强度
    WAYPOINTS_INTERVAL: 2    # 关键帧间隔 8
    OBSTACLE_MODE: False      # 避障模式 (暂关)
    OBSTACLE_GUIDE_STRENGTH: 100.0
    MAX_NORM: 2            # 梯度裁剪阈值 0.5  
    
    # 轨迹形状参数
    SHAPE: 'straight'         # 可选: straight, left, right, s_curve, 'straight_then_left', 'straight_then_right','backward' ,backward_left
    SPEED: 0.04               # 速度 (米/帧)
    TURN_START: 80            # 转弯开始帧
    CURVE_AMPLITUDE: 2.0      # 弯曲幅度


    # === 新增天花板配置 ===
    CEILING_MODE: False        # 开关
    # CEILING_HEIGHT: 1.3    # 限制高度 
    # [新增] 时序天花板: [开始帧, 结束帧, 高度]
    # 这里的 9999 代表“直到最后”
    CEILING_TIMELINE:
        - [0, 80, 2.5]      # 0-60帧: 高度0.9米 (强制蹲下/爬行)
        - [80, 9999, 0.8]   # 60帧-结束: 高度2.5米 (解除限制，可以站起来)
                             
    CEILING_STRENGTH: 10.0  # 惩罚力度
    
    # === [新增] 安全距离 (皮肤厚度 + 缓冲) ===
    # 建议 0.10 ~ 0.15 米 (10cm - 15cm)
    SAFETY_MARGIN: 0.10

    # === [新增] 狭窄缝隙配置 ===
    GAP_MODE:  False    
    # GAP_WIDTH: 0.5          # 缝隙宽度 (米)。正常人肩宽约 0.45-0.5m。
    #                           # 设为 0.5 意味着左右只有 0.25 的空间，非常极限，必须夹着手走。
    # [新增] 时序缝隙: [开始帧, 结束帧, 宽度(米)]
    # 假设人肩宽 0.45m。设为 0.5m 非常极限，必须侧身。
    # 时序缝隙: [Start, End, Width]
    # GAP_TIMELINE:
    #     - [0, 60, 2.0]     # 宽敞
    #     - [60, 140, 0.5]   # 变窄
    #     - [140, 9999, 2.0] # 恢复
    GAP_TIMELINE:
        # - [0, 60, 5.5]     # 宽敞
        # - [60, 9999, 0.5]   # 变窄
        # # - [140, 9999, 2.0] # 恢复
        
        # - [0, 40, 5.5]     # 宽敞
        # - [40, 80, 0.5]     # 宽敞
        # - [80, 9999, 5.5]   # 只有中间这段强制侧身

        - [0, 60, 5.5]     # 宽敞
        - [60, 80, 0.5]     # 宽敞
        - [80, 9999, 5.5]   # 只有中间这段强制侧身

    GAP_STRENGTH: 40000.0      # 惩罚力度
    SAFETY_MARGIN_GAP: 0.5

    # === [新增] 侧身引导 ===
    SIDE_STEP_MODE: True 

    # [核心新增] 时序侧身: [Start, End, 1.0] 
    # 第三位写 1.0 代表开启侧身，写 0.0 代表关闭
    SIDE_STEP_TIMELINE:
        - [0, 60, 0.0]     # 宽敞
        - [60, 80, 1.0]     # 宽敞
        - [80, 9999, 0.0]   # 只有中间这段强制侧身
        # - [100, 9999, 5.5]     # 宽敞

    # 当 GAP_WIDTH 小于此阈值时，强制开启侧身引导
    SIDE_STEP_THRESHOLD: 2.5  # 暂时让它无论如何都开启）
    SIDE_STEP_STRENGTH: 500000.0 # 旋转惩罚力度

    

#####################################
# Visualization Settings
#####################################
VISUALIZATION:
  SIDE_VIEW_EXPORT: False  # 开关：是否生成侧视图调试视频
  TOP_VIEW_EXPORT: False   # 开关：是否生成顶视图调试视频
  # FRONT_VIEW_EXPORT: True # 开关：是否生成前视图调试视频