# mld/configs/config_sanity_check.yaml
# 这是一个专门用于运行 sanity_check.py 脚本的、完全自包含的配置文件。
# 它整合了基础路径配置和混合训练的详细配置。

# --- Hydra Defaults ---
# 这告诉 Hydra 从这个文件本身加载配置
defaults:
  - _self_

# --- 基础路径配置 (来自你的第二份 yaml 文件) ---
FOLDER: './experiments'
TEST:
  FOLDER: './results'

# --- 核心配置 (来自你的 config_mld_mixed.yaml) ---

# 实验设置
NAME: SanityCheck_Run
DEBUG: False # 设为 False 以使用完整数据集进行检查
ACCELERATOR: 'gpu'
DEVICE: [0]

# 训练设置 (仅用于驱动 DataModule)
TRAIN:
  STAGE: diffusion
  DATASETS: ['mixed']
  NUM_WORKERS: 8
  BATCH_SIZE: 128 # 保持与你训练时一致

# 验证设置 (暂时用不到，但保持完整性)
EVAL:
  DATASETS: ['humanml3d']
  BATCH_SIZE: 64
  SPLIT: val

# [关键] 数据集设置
DATASET:
  # 基础信息
  JOINT_TYPE: 'humanml3d'
  NFEATS: 263
  NJOINTS: 22
  TYPE: 'mixed'

  # 基础路径
  SMPL_PATH: 'deps/smpl'
  TRANSFORM_PATH: 'deps/transforms/'
  WORD_VERTILIZER_PATH: 'deps/t2m/glove/'

  # 混合数据集配置
  MIXED:
    # 比例: [HumanML3D, 100Style]. 和 BATCH_SIZE 保持一致
    # 这里的值将决定我们在日志中看到的两种样本的数量
    BATCH_RATIO: [64, 64]

  # HumanML3D 数据集配置 (使用你的绝对路径)
  HUMANML3D:
    ROOT: "/root/autodl-tmp/MyRepository/MCM-LDM/datasets/humanml3d"
    SPLIT_ROOT: "/root/autodl-tmp/MyRepository/MCM-LDM/datasets/humanml3d"
    SAMPLER: {MAX_LEN: 196, MIN_LEN: 40, MAX_TEXT_LEN: 20}
    UNIT_LEN: 4
    MIN_FILTER_LEN: 40
    MAX_FILTER_LEN: 200

  # 100Style 数据集配置 (使用你的绝对路径)
  STYLE100:
    ROOT: "/root/autodl-tmp/MyRepository/MCM-LDM/datasets/100StyleDataset"
    SPLIT_ROOT: "/root/autodl-tmp/MyRepository/MCM-LDM/datasets/100StyleDataset"
    SAMPLER: {MAX_LEN: 196, MIN_LEN: 40, MAX_TEXT_LEN: 20}
    UNIT_LEN: 4
    MIN_FILTER_LEN: 40
    MAX_FILTER_LEN: 720

# [关键] 模型设置 (DataModule 会读取这里的路径)
model:
  clip_path: 'deps/clip-vit-large-patch14'
  t2m_path: 'deps/t2m/t2m'
  
  # 其他模型参数 (对于数据检查不重要，但保持完整)
  vae: true
  model_type: mld
  condition: 'text'
  latent_dim: [7, 256]
  ff_size: 1024
  num_layers: 9
  num_head: 4
  droupout: 0.1
  activation: gelu
  guidance_scale: 5.0
  guidance_uncondp: 0.1
  denoiser:
    use_text_condition: True
    clip_feature_dim: 512